name: Deploy playwight-multi-crawler systemd

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 배포 폴더로 이동 및 코드 업데이트
            export PATH="$HOME/.local/bin:$PATH"  # 환경 변수 추가
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}

            if [ ! -d ".git" ]; then
              git clone https://github.com/humaningansalam/playwright-multi-crawler.git .
            else
              git pull origin main
            fi

            # Poetry 설치 및 Playwright 종속성 설치
            portey install
            poetry run playwright install-deps 
            poetry run playwright install chromium


            # 서비스 파일의 경로를 설정한 Secrets 변수를 사용해 동적으로 수정
            sed -i "s|/path/to/your/deployment/folder|${{ secrets.DEPLOY_PATH }}|g" ${{ secrets.DEPLOY_PATH }}/config/playwright-multi-crawler.service
            sed -i "s|your_user|${{ secrets.SERVER_USER }}|g" ${{ secrets.DEPLOY_PATH }}/config/playwright-multi-crawler.service

            # systemd 서비스 파일 복사 및 활성화
            sudo cp ${{ secrets.DEPLOY_PATH }}/config/playwright-multi-crawler.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl enable playwright-multi-crawler
            sudo systemctl restart playwright-multi-crawler
