name: Deploy playwight-multi-crawler systemd

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            
            set -e  # 에러 발생 시 중단

            # 배포 폴더로 이동 및 코드 업데이트
            export PATH="$HOME/.local/bin:$PATH"  # 환경 변수 추가
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}

            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git fetch --all
              git reset --hard origin/main 
            fi

            # .env 파일 생성
            echo "PORT=${{ vars.SERVER_PORT }}" > ${{ secrets.DEPLOY_PATH }}/.env
            echo "DISPLAY=${{ vars.DISPLAY }}" >> ${{ secrets.DEPLOY_PATH }}/.env

            # 실행 권한 부여
            chmod +x ./config/install_dependencies.sh
            ./config/install_dependencies.sh

            # systemd 서비스 파일 생성
            echo "[Unit]
            Description=Playwright Multi Crawler Service
            After=network.target

            [Service]
            Type=simple
            User=${{ secrets.SERVER_USER }}
            WorkingDirectory=${{ secrets.DEPLOY_PATH }}
            ExecStart=/home/${{ secrets.SERVER_USER }}/.local/bin/poetry run python -m myapp.main
            Restart=on-failure
            RestartSec=10  
            StartLimitInterval=30
            StartLimitBurst=5  

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/playwright-multi-crawler.service

            # systemd 데몬 다시 로드하고 서비스 시작
            sudo systemctl daemon-reload
            sudo systemctl enable playwright-multi-crawler
            sudo systemctl restart playwright-multi-crawler
